export const SECURITY_THEMES = {
  command: {
    id: "command",
    name: "Command Blue",
    primary: "#061224",
    secondary: "#0f3b78",
    accent: "#2563eb",
    accent2: "#22c55e",
    surface: "#f5f8fc",
    card: "#ffffff",
    text: "#0f172a",
    muted: "#64748b",
    line: "#dbe6f5",
  },
  matrix: {
    id: "matrix",
    name: "Surveillance Matrix",
    primary: "#020617",
    secondary: "#063c3b",
    accent: "#14b8a6",
    accent2: "#38bdf8",
    surface: "#effdfa",
    card: "#ffffff",
    text: "#0f172a",
    muted: "#64748b",
    line: "#c7f2ed",
  },
  executive: {
    id: "executive",
    name: "Executive Gold",
    primary: "#111111",
    secondary: "#2a2118",
    accent: "#b8892e",
    accent2: "#eab308",
    surface: "#f7f3ea",
    card: "#fffdf8",
    text: "#1f2937",
    muted: "#6b7280",
    line: "#eadfca",
  },
  event: {
    id: "event",
    name: "Event Response",
    primary: "#1f1010",
    secondary: "#7f1d1d",
    accent: "#ef4444",
    accent2: "#f97316",
    surface: "#fff7ed",
    card: "#ffffff",
    text: "#111827",
    muted: "#6b7280",
    line: "#fed7aa",
  },

  patrol: {
    id: "patrol",
    name: "Mobile Patrol Navy",
    primary: "#07111f",
    secondary: "#164e63",
    accent: "#06b6d4",
    accent2: "#84cc16",
    surface: "#f0f9ff",
    card: "#ffffff",
    text: "#0f172a",
    muted: "#64748b",
    line: "#bae6fd",
  },
  alarm: {
    id: "alarm",
    name: "Alarm Response Amber",
    primary: "#18110a",
    secondary: "#92400e",
    accent: "#f59e0b",
    accent2: "#ef4444",
    surface: "#fffbeb",
    card: "#ffffff",
    text: "#111827",
    muted: "#6b7280",
    line: "#fde68a",
  },
  industrial: {
    id: "industrial",
    name: "Industrial Steel",
    primary: "#0f172a",
    secondary: "#334155",
    accent: "#f97316",
    accent2: "#facc15",
    surface: "#f8fafc",
    card: "#ffffff",
    text: "#0f172a",
    muted: "#64748b",
    line: "#cbd5e1",
  },
  estate: {
    id: "estate",
    name: "Estate Emerald",
    primary: "#052e2b",
    secondary: "#047857",
    accent: "#10b981",
    accent2: "#a7f3d0",
    surface: "#ecfdf5",
    card: "#ffffff",
    text: "#064e3b",
    muted: "#64748b",
    line: "#a7f3d0",
  },
  systems: {
    id: "systems",
    name: "Integrated Systems Blue",
    primary: "#020617",
    secondary: "#1d4ed8",
    accent: "#60a5fa",
    accent2: "#22d3ee",
    surface: "#eff6ff",
    card: "#ffffff",
    text: "#0f172a",
    muted: "#64748b",
    line: "#bfdbfe",
  },
  retail: {
    id: "retail",
    name: "Retail Hospitality Plum",
    primary: "#1e122d",
    secondary: "#6d28d9",
    accent: "#a855f7",
    accent2: "#f0abfc",
    surface: "#faf5ff",
    card: "#ffffff",
    text: "#1f2937",
    muted: "#64748b",
    line: "#e9d5ff",
  },
};

export const SECURITY_SOCIAL_DEFAULTS = {
  guarding: [
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
  ],
  surveillance: [
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "youtube", label: "YouTube", short: "yt", url: "https://youtube.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
    { key: "email", label: "Email", short: "@", url: "mailto:info@securitycompany.co.za" },
  ],
  executive: [
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "email", label: "Email", short: "@", url: "mailto:confidential@securitycompany.co.za" },
    { key: "phone", label: "Phone", short: "☎", url: "tel:+27000000000" },
  ],
  event: [
    { key: "instagram", label: "Instagram", short: "ig", url: "https://instagram.com" },
    { key: "tiktok", label: "TikTok", short: "tk", url: "https://tiktok.com" },
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
  ],

  patrol: [
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
    { key: "phone", label: "Phone", short: "☎", url: "tel:+27000000000" },
  ],
  alarm: [
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "email", label: "Email", short: "@", url: "mailto:response@securitycompany.co.za" },
    { key: "phone", label: "Phone", short: "☎", url: "tel:+27000000000" },
  ],
  industrial: [
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "youtube", label: "YouTube", short: "yt", url: "https://youtube.com" },
    { key: "email", label: "Email", short: "@", url: "mailto:industrial@securitycompany.co.za" },
  ],
  estate: [
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
  ],
  systems: [
    { key: "linkedin", label: "LinkedIn", short: "in", url: "https://linkedin.com" },
    { key: "youtube", label: "YouTube", short: "yt", url: "https://youtube.com" },
    { key: "x", label: "X", short: "x", url: "https://x.com" },
    { key: "email", label: "Email", short: "@", url: "mailto:systems@securitycompany.co.za" },
  ],
  retail: [
    { key: "instagram", label: "Instagram", short: "ig", url: "https://instagram.com" },
    { key: "facebook", label: "Facebook", short: "f", url: "https://facebook.com" },
    { key: "tiktok", label: "TikTok", short: "tk", url: "https://tiktok.com" },
    { key: "whatsapp", label: "WhatsApp", short: "wa", url: "https://wa.me/27000000000" },
  ],
};

export const SECURITY_IMAGE_PACKS = {
  guarding: {
    hero: "https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      {
        type: "image",
        title: "Professional Guarding & Access Control",
        subtitle: "Disciplined officers, clear post orders and reliable daily reporting.",
        image: "https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "image",
        title: "Residential, School & Commercial Protection",
        subtitle: "Visible patrols and visitor control for sites that need professional presence.",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "video",
        title: "24/7 Guarding Operations",
        subtitle: "Use your own company video or keep the professional poster image.",
        image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1900&q=82",
        video: "https://videos.pexels.com/video-files/3255275/3255275-uhd_2560_1440_25fps.mp4",
      },
    ],
  },
  surveillance: {
    hero: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      {
        type: "image",
        title: "CCTV Monitoring & Control-Room Support",
        subtitle: "Camera visibility, event verification and evidence-led incident reporting.",
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "video",
        title: "Remote Monitoring Workflows",
        subtitle: "A technology-first template for CCTV, alarm and control-room providers.",
        image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1900&q=82",
        video: "https://videos.pexels.com/video-files/3209828/3209828-uhd_2560_1440_25fps.mp4",
      },
      {
        type: "image",
        title: "Incident Verification & Escalation",
        subtitle: "Show clients how events are reviewed, confirmed and escalated professionally.",
        image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1900&q=82",
      },
    ],
  },
  executive: {
    hero: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      {
        type: "image",
        title: "Executive Protection & Risk Advisory",
        subtitle: "A refined digital presence for corporate security and private protection providers.",
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "image",
        title: "Discreet Planning For High-Value Clients",
        subtitle: "Premium pages for close protection, secure transport and sensitive environments.",
        image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "video",
        title: "Corporate Security Confidence",
        subtitle: "Use video to present professionalism, discretion and executive-level trust.",
        image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1900&q=82",
        video: "https://videos.pexels.com/video-files/3184465/3184465-uhd_2560_1440_25fps.mp4",
      },
    ],
  },
  event: {
    hero: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      {
        type: "image",
        title: "Event Security & Crowd Control",
        subtitle: "Protect entrances, VIP zones, stages, parking and high-traffic event areas.",
        image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1900&q=82",
      },
      {
        type: "video",
        title: "Venue Safety Operations",
        subtitle: "A bold template for concerts, conferences, church events, sports days and festivals.",
        image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1900&q=82",
        video: "https://videos.pexels.com/video-files/2775442/2775442-uhd_2560_1440_25fps.mp4",
      },
      {
        type: "image",
        title: "Emergency-Ready Event Teams",
        subtitle: "Show deployment plans, control points, briefing systems and rapid escalation paths.",
        image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1900&q=82",
      },
    ],
  },

  patrol: {
    hero: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1465447142348-e9952c393450?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Mobile Patrol & Rapid Site Response", subtitle: "Visible vehicle patrols, route checks, lock-up support and after-hours attendance.", image: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Patrol Routes With Real Accountability", subtitle: "Present route coverage, checkpoint verification and escalation support in a professional way.", image: "https://images.unsplash.com/photo-1465447142348-e9952c393450?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/3121459/3121459-uhd_2560_1440_24fps.mp4" },
      { type: "image", title: "After-Hours Security For Multiple Sites", subtitle: "Ideal for estates, warehouses, offices, schools and construction sites needing mobile coverage.", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1900&q=82" },
    ],
  },
  alarm: {
    hero: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Alarm Response & Emergency Dispatch", subtitle: "A response-focused template for companies offering alarm reaction and escalation support.", image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Reaction Teams Built Around Speed", subtitle: "Show response procedures, verification steps and support channels for urgent incidents.", image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/3209829/3209829-uhd_2560_1440_25fps.mp4" },
      { type: "image", title: "Verified Alerts, Clear Escalation", subtitle: "Help customers understand how alerts become action through documented response workflows.", image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1900&q=82" },
    ],
  },
  industrial: {
    hero: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Industrial & Construction Site Security", subtitle: "Secure yards, warehouses, factories, logistics areas and high-risk operational sites.", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1900&q=82" },
      { type: "image", title: "Asset Protection For Operational Environments", subtitle: "Focus on gate control, contractor management, patrols, safety alignment and stock-loss prevention.", image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Security For Moving Sites", subtitle: "A practical structure for companies serving construction, warehousing and logistics clients.", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/856971/856971-hd_1920_1080_25fps.mp4" },
    ],
  },
  estate: {
    hero: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Estate & Residential Security Management", subtitle: "Professional gatehouse control, resident access, visitor screening and patrol coordination.", image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Community-Focused Protection", subtitle: "Show residents and body corporates a calm, polished and trustworthy security presence.", image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/3773486/3773486-uhd_2560_1440_30fps.mp4" },
      { type: "image", title: "Gate Control, Patrols & Resident Support", subtitle: "A residential security template for estates, complexes, apartments and neighbourhood patrols.", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1900&q=82" },
    ],
  },
  systems: {
    hero: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Integrated Security Systems & Access Control", subtitle: "CCTV, access control, alarms, intercoms and security technology presented in one professional template.", image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Technology-Led Site Protection", subtitle: "Ideal for installers and system integrators who want to explain hardware, monitoring and maintenance.", image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/3209828/3209828-uhd_2560_1440_25fps.mp4" },
      { type: "image", title: "Install, Maintain & Support", subtitle: "Use service cards for installation, maintenance, audits, integrations and support plans.", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1900&q=82" },
    ],
  },
  retail: {
    hero: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1900&q=82",
    about: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1500&q=82",
    page: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1700&q=82",
    gallery: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1300&q=82",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1300&q=82",
    ],
    slides: [
      { type: "image", title: "Retail & Hospitality Security Services", subtitle: "Customer-friendly security for shops, malls, hotels, restaurants and public-facing venues.", image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1900&q=82" },
      { type: "video", title: "Loss Prevention With A Professional Front", subtitle: "Balance security presence with a welcoming brand experience for guests and customers.", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1900&q=82", video: "https://videos.pexels.com/video-files/3184465/3184465-uhd_2560_1440_25fps.mp4" },
      { type: "image", title: "Hotels, Shops & Guest-Facing Sites", subtitle: "A polished template for security providers who protect service environments.", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1900&q=82" },
    ],
  },
};

export const SECURITY_TEMPLATE_CONTENT = {
  guarding: {
    businessName: "Sentinel Guarding Services",
    tagline: "Disciplined guarding, access control and patrol services for commercial, residential and public sites.",
    motto: "Visible. Accountable. Ready.",
    heroTitle: "Professional guarding that protects people, property and daily operations.",
    heroSubtitle: "Deploy trained officers, manage access points, improve visitor control and keep your site visible, documented and protected around the clock.",
    heroCta: "Book Site Assessment",
    heroSecondaryCta: "View Guarding Services",
    aboutTitle: "A guarding partner built around discipline, visibility and reporting.",
    aboutText: "Our guarding teams support offices, schools, estates, warehouses, retail centres and construction sites with professional presence, visitor control, patrols and incident documentation.",
    vision: "To be the trusted guarding partner for organisations that need visible protection and reliable accountability.",
    mission: "To deliver trained officers, clear site procedures and practical reporting that improves safety every day.",
    values: ["Discipline", "Visibility", "Integrity", "Responsiveness"],
    services: [
      { title: "Static Guarding", text: "Uniformed officers for entrances, reception points, gatehouses, warehouses, schools, offices and estates." },
      { title: "Access Control", text: "Visitor registers, vehicle checks, contractor sign-in, delivery control and entry procedures aligned to site policy." },
      { title: "Patrol Management", text: "Scheduled patrols, perimeter checks, lock-up support, hotspot visibility and shift handover reporting." },
      { title: "Retail & Commercial Security", text: "Professional presence for malls, shops, offices and mixed-use sites with customer-friendly conduct." },
      { title: "Estate & Residential Security", text: "Gate control, visitor screening, patrols and resident-support procedures for residential communities." },
      { title: "Incident Reporting", text: "Structured incident notes, escalation paths and daily reports so management can see what happened on site." },
    ],
    solutions: ["Gatehouse and visitor management", "Day and night security officer deployment", "Commercial property patrols", "School and campus access control"],
    industries: ["Offices", "Schools", "Estates", "Retail", "Warehouses", "Construction Sites"],
    features: ["Supervisor check-ins", "Post orders", "Daily occurrence book", "Emergency escalation", "Visitor registers", "Uniformed officers"],
    packages: [
      { title: "Essential Site Guarding", text: "Ideal for entrances, day posts and visitor reception control." },
      { title: "24/7 Guarding Team", text: "Day and night shifts with supervisor support and reporting." },
      { title: "Estate Protection Plan", text: "Gate control, patrol routes, visitor screening and resident support." },
    ],
    stats: [["24/7", "Guarding availability"], ["Visible", "Site presence"], ["Daily", "Shift reports"], ["Fast", "Escalation support"]],
    process: ["Assess posts, risks and access points", "Create post orders and deployment plan", "Deploy trained officers and supervisors", "Review reports and improve site procedures"],
    testimonials: [
      { quote: "The guarding team improved our visitor process and after-hours site visibility from the first week.", author: "Facilities Manager" },
      { quote: "Professional officers, good reporting and reliable communication with our management team.", author: "Estate Operations Lead" },
    ],
    contactTitle: "Request a guarding assessment for your site.",
    contactIntro: "Tell us about your site, number of posts and preferred coverage. We will respond with a professional deployment recommendation.",
  },
  surveillance: {
    businessName: "Matrix Surveillance Control",
    tagline: "CCTV monitoring, alarm response coordination and technology-supported security operations.",
    motto: "Monitor. Verify. Escalate.",
    heroTitle: "CCTV monitoring and control-room support for modern security operations.",
    heroSubtitle: "Combine camera visibility, incident verification, escalation procedures and site reporting to improve awareness before small risks become serious problems.",
    heroCta: "Plan Monitoring Setup",
    heroSecondaryCta: "Explore CCTV Services",
    aboutTitle: "A surveillance-first design for monitoring and response companies.",
    aboutText: "This template is designed for CCTV installers, monitoring teams, alarm-response coordinators and technical security providers that need a professional technology-driven website.",
    vision: "To help clients move from reactive security to informed, monitored and evidence-led operations.",
    mission: "To provide dependable camera monitoring, event verification and escalation support through clear procedures and smart technology.",
    values: ["Awareness", "Accuracy", "Speed", "Evidence"],
    services: [
      { title: "CCTV Monitoring", text: "Control-room style monitoring support, observation routines, suspicious-activity escalation and documented reporting." },
      { title: "Camera System Review", text: "Site camera coverage review, blind-spot identification and practical improvement recommendations." },
      { title: "Alarm Verification", text: "Event verification workflow to reduce false alarms and escalate confirmed concerns to the right response team." },
      { title: "Remote Site Visibility", text: "Monitoring-ready presentation for warehouses, estates, construction sites, schools and commercial premises." },
      { title: "Incident Evidence Support", text: "Clear incident timelines, camera references and reporting support for management review." },
      { title: "Technical Security Consulting", text: "Recommendations for cameras, access points, lighting, procedures and monitoring operations." },
    ],
    solutions: ["CCTV control-room monitoring", "Camera coverage review", "Alarm event verification", "Incident footage and reporting workflow"],
    industries: ["Warehouses", "Retail", "Estates", "Schools", "Business Parks", "Construction Sites"],
    features: ["Camera audits", "Event verification", "Alarm escalation", "Incident timelines", "Remote visibility", "Coverage reporting"],
    packages: [
      { title: "Camera Coverage Audit", text: "Review blind spots, risk areas and monitoring opportunities." },
      { title: "Remote Monitoring Setup", text: "Monitoring procedures, escalation rules and incident documentation." },
      { title: "Control-Room Support", text: "A professional workflow for sites with multiple cameras and alerts." },
    ],
    stats: [["Live", "Monitoring workflows"], ["Clear", "Camera coverage"], ["Verified", "Event escalation"], ["Logged", "Incident history"]],
    process: ["Review site cameras and risk areas", "Define monitoring rules and alert priorities", "Verify events before escalation", "Document outcomes and recommend improvements"],
    testimonials: [
      { quote: "The monitoring workflow helped us understand incidents faster and improve our camera coverage.", author: "Warehouse Site Manager" },
      { quote: "Their reporting made our security operations easier to review and manage.", author: "Commercial Property Manager" },
    ],
    contactTitle: "Speak to a surveillance specialist.",
    contactIntro: "Share your camera count, site type and monitoring needs so the team can recommend a professional surveillance plan.",
  },
  executive: {
    businessName: "Executive Shield Protection",
    tagline: "Premium corporate protection, VIP support and risk advisory for leadership teams and high-value operations.",
    motto: "Discreet. Strategic. Professional.",
    heroTitle: "Premium executive protection and risk advisory for serious organisations.",
    heroSubtitle: "A refined security brand for corporate clients, executives, private offices and organisations that need trust, discretion and professional planning.",
    heroCta: "Request Confidential Consultation",
    heroSecondaryCta: "View Protection Services",
    aboutTitle: "A premium security design for corporate and executive protection providers.",
    aboutText: "Executive protection requires a different level of presentation. This template uses premium visuals, refined spacing and trust-focused content for clients who expect professionalism and discretion.",
    vision: "To become the preferred protection partner for leaders, private clients and organisations with sensitive security requirements.",
    mission: "To deliver discreet planning, professional protection and risk-aware support for people, assets and reputation.",
    values: ["Discretion", "Trust", "Precision", "Professionalism"],
    services: [
      { title: "Executive Protection", text: "Close protection planning, movement support and secure coordination for executives and private clients." },
      { title: "Corporate Risk Advisory", text: "Security planning for offices, leadership teams, sensitive meetings and high-value environments." },
      { title: "Secure Transport Coordination", text: "Journey planning, arrival protocols and discreet movement support for priority clients." },
      { title: "VIP Event Support", text: "Access control, holding areas, itinerary protection and guest movement planning." },
      { title: "Residential Security Review", text: "Private property review, access-point recommendations and practical safety procedures." },
      { title: "Confidential Consultation", text: "A professional intake flow for clients who need sensitive security support without public exposure." },
    ],
    solutions: ["Executive movement planning", "VIP event support", "Private office security review", "Secure transport coordination"],
    industries: ["Executives", "Private Clients", "Law Firms", "Corporate Offices", "Diplomatic Guests", "High-Value Events"],
    features: ["Confidential intake", "Risk advisory", "VIP protocols", "Journey planning", "Executive liaison", "Private consultation"],
    packages: [
      { title: "Private Consultation", text: "Confidential review of executive or family security needs." },
      { title: "Executive Movement Plan", text: "Planning for routes, arrivals, schedules and sensitive meetings." },
      { title: "Corporate Protection Retainer", text: "Ongoing security advisory and professional response planning." },
    ],
    stats: [["Private", "Client intake"], ["Premium", "Protection planning"], ["Trusted", "Advisory process"], ["Discreet", "Client support"]],
    process: ["Confidential client intake", "Risk and movement planning", "Deployment and liaison", "Post-operation review and recommendations"],
    testimonials: [
      { quote: "The process was professional, discreet and well structured from the first consultation.", author: "Corporate Client" },
      { quote: "Their planning gave our leadership team confidence during a high-profile engagement.", author: "Executive Office Manager" },
    ],
    contactTitle: "Request a confidential protection consultation.",
    contactIntro: "Use this confidential form for executive protection, VIP support, secure movement or risk advisory enquiries.",
  },
  event: {
    businessName: "Event Shield Operations",
    tagline: "Event security, access control, crowd management and venue safety support for organisers.",
    motto: "Plan. Control. Protect.",
    heroTitle: "Event security that keeps guests moving, venues controlled and organisers confident.",
    heroSubtitle: "A bold, high-energy template for concerts, conferences, sports days, church events, school events and private functions.",
    heroCta: "Plan Event Security",
    heroSecondaryCta: "View Event Services",
    aboutTitle: "Built for event security companies that need a strong operational presence.",
    aboutText: "Event security is about planning, control points, guest movement, quick communication and professional conduct. This design helps event companies explain their capability clearly.",
    vision: "To support safer events with trained teams, structured access control and visible operational coordination.",
    mission: "To help organisers reduce event risk through clear deployment plans, professional teams and responsive communication.",
    values: ["Control", "Communication", "Readiness", "Professional Conduct"],
    services: [
      { title: "Event Access Control", text: "Entrance screening, wristband checks, ticket-flow support and restricted-area control." },
      { title: "Crowd Management", text: "Visible teams for queues, high-density areas, stage zones and guest movement support." },
      { title: "VIP & Backstage Security", text: "Controlled access for artists, speakers, VIP guests, staff-only areas and production teams." },
      { title: "Parking & Perimeter Support", text: "Vehicle flow, perimeter checks, gate support and arrival/departure visibility." },
      { title: "Emergency Readiness", text: "Escalation paths, communication roles and incident procedures for safer event delivery." },
      { title: "Event Risk Planning", text: "Pre-event walk-throughs, risk areas, staff briefings, control points and deployment recommendations." },
    ],
    solutions: ["Concert and festival security", "Conference and expo safety", "School and sports-day security", "Church and community events"],
    industries: ["Concerts", "Conferences", "Church Events", "School Events", "Sports Events", "Private Functions"],
    features: ["Access gates", "VIP zones", "Crowd movement", "Parking control", "Radio protocol", "Emergency readiness"],
    packages: [
      { title: "Small Event Coverage", text: "Entrances, guest flow and basic event risk support." },
      { title: "Venue Control Plan", text: "Stage, VIP, parking, backstage and perimeter deployment." },
      { title: "Large Event Operations", text: "Multiple zones, supervisors, radio protocol and emergency escalation." },
    ],
    stats: [["Planned", "Access points"], ["Visible", "Crowd support"], ["Ready", "Escalation flow"], ["Clear", "Briefing structure"]],
    process: ["Review event layout and expected attendance", "Define zones, posts and communication roles", "Brief teams and manage event operations", "Debrief and provide improvement notes"],
    testimonials: [
      { quote: "The team handled guest flow and VIP access professionally throughout our event.", author: "Event Organiser" },
      { quote: "Clear planning, strong presence and quick communication made the day easier to manage.", author: "Venue Manager" },
    ],
    contactTitle: "Plan security for your next event.",
    contactIntro: "Share your event date, venue, expected attendance and security needs for an event deployment recommendation.",
  },

  patrol: {
    businessName: "Patrol Response Security",
    tagline: "Mobile patrols, lock-up support, after-hours response and route-based security visibility.",
    motto: "Patrol. Verify. Respond.",
    heroTitle: "Mobile patrol security for sites that need visible coverage and fast response.",
    heroSubtitle: "Protect multiple locations with vehicle patrols, checkpoint verification, lock-up support, alarm attendance and clear reporting for managers.",
    heroCta: "Request Patrol Plan",
    heroSecondaryCta: "View Patrol Services",
    aboutTitle: "Route-based protection for organisations with more than one risk point.",
    aboutText: "This template is built for security companies offering mobile patrols, response vehicles, lock-up support and after-hours site visibility across estates, warehouses, schools and business parks.",
    vision: "To make mobile security visible, measurable and reliable for every client site.",
    mission: "To deliver route-based patrol coverage with clear checkpoints, fast escalation and practical response support.",
    values: ["Mobility", "Accountability", "Speed", "Visibility"],
    services: [
      { title: "Mobile Patrols", text: "Scheduled patrols across multiple sites with visible vehicle presence and documented checkpoint activity." },
      { title: "Lock-Up & Unlock Support", text: "Opening and closing support for offices, schools, warehouses and retail sites requiring after-hours checks." },
      { title: "Alarm Attendance", text: "Response attendance after alerts with verification, escalation and client communication." },
      { title: "Perimeter Inspections", text: "Fence lines, gates, parking areas and high-risk points checked according to a route plan." },
      { title: "Vacant Property Checks", text: "Regular inspections for vacant units, construction sites and assets needing visible protection." },
      { title: "Route Reporting", text: "Daily activity notes, incident updates and checkpoint summaries for management review." },
    ],
    solutions: ["Multi-site patrol routes", "After-hours property checks", "Alarm response attendance", "Lock-up and unlock schedules"],
    industries: ["Business Parks", "Warehouses", "Schools", "Estates", "Retail", "Vacant Properties"],
    features: ["Route planning", "Checkpoint logs", "Vehicle patrols", "Supervisor review", "Alarm attendance", "After-hours support"],
    packages: [
      { title: "Night Patrol Route", text: "Scheduled night inspections for selected client sites." },
      { title: "Multi-Site Coverage", text: "Route planning and response for several nearby properties." },
      { title: "Patrol + Alarm Support", text: "Patrol visibility combined with verified alarm attendance." },
    ],
    stats: [["Route", "Patrol planning"], ["Fast", "Alarm attendance"], ["Logged", "Checkpoint visits"], ["Mobile", "Visible response"]],
    process: ["Map sites and patrol priorities", "Build route schedule and checkpoint plan", "Deploy patrol teams and response vehicle", "Report visits, incidents and recommendations"],
    testimonials: [
      { quote: "The patrol route gave our properties after-hours visibility without placing a full-time officer at every site.", author: "Property Portfolio Manager" },
      { quote: "Reports are clear and our team knows exactly when checks are completed.", author: "Operations Supervisor" },
    ],
    contactTitle: "Request a mobile patrol plan.",
    contactIntro: "Share your site locations, hours and patrol frequency so the team can recommend the right route coverage.",
  },
  alarm: {
    businessName: "Rapid Alarm Response Unit",
    tagline: "Alarm response, alert verification, emergency escalation and response coordination for protected sites.",
    motto: "Alert. Verify. Act.",
    heroTitle: "Alarm response services built for urgent incidents and clear escalation.",
    heroSubtitle: "A professional template for armed response, alarm attendance, dispatch coordination and emergency support companies.",
    heroCta: "Get Response Plan",
    heroSecondaryCta: "View Response Services",
    aboutTitle: "A response-first design for alert-driven security companies.",
    aboutText: "This template highlights speed, verification, dispatch procedures and client communication for companies responding to alarms, incidents and emergency support requests.",
    vision: "To become a reliable response partner when alerts require quick verification and action.",
    mission: "To verify alerts, coordinate response and keep clients informed through clear procedures and professional teams.",
    values: ["Readiness", "Speed", "Control", "Communication"],
    services: [
      { title: "Alarm Response", text: "Attendance after alarms with verification, escalation and client updates according to response procedure." },
      { title: "Alert Verification", text: "Review and confirm alerts before escalation to reduce false responses and improve accountability." },
      { title: "Emergency Support", text: "Rapid coordination for incidents, after-hours threats, suspicious activity and urgent site concerns." },
      { title: "Dispatch Coordination", text: "Response routing, client communication and incident tracking from first alert to closure." },
      { title: "Keyholder Support", text: "Structured callout support and safe arrival coordination with authorised site representatives." },
      { title: "Incident Follow-Up", text: "Post-incident notes, escalation summary and prevention recommendations for management." },
    ],
    solutions: ["Alarm callout attendance", "Emergency site support", "Keyholder response", "Dispatch and escalation workflow"],
    industries: ["Homes", "Retail", "Offices", "Warehouses", "Estates", "Small Businesses"],
    features: ["Response protocol", "Dispatch flow", "Alert verification", "Client updates", "Incident notes", "Emergency readiness"],
    packages: [
      { title: "Basic Alarm Attendance", text: "Response attendance and alert outcome reporting." },
      { title: "Priority Response Plan", text: "Urgent callout support with escalation procedures." },
      { title: "Business Protection Plan", text: "Response support for offices, shops and warehouses." },
    ],
    stats: [["Alert", "Verification"], ["Rapid", "Dispatch"], ["Ready", "Emergency flow"], ["Clear", "Client updates"]],
    process: ["Receive alert or request", "Verify details and response priority", "Dispatch response team", "Report outcome and next steps"],
    testimonials: [
      { quote: "The response process is clear and our managers receive proper updates after each callout.", author: "Business Owner" },
      { quote: "They helped us create a better alarm escalation process for our premises.", author: "Retail Manager" },
    ],
    contactTitle: "Build your alarm response plan.",
    contactIntro: "Tell us about your alarm system, site type and response coverage needed.",
  },
  industrial: {
    businessName: "Industrial Shield Security",
    tagline: "Security for warehouses, construction sites, logistics yards, factories and industrial operations.",
    motto: "Secure. Control. Protect.",
    heroTitle: "Industrial security for high-value assets, access points and operational sites.",
    heroSubtitle: "Protect stock, equipment, yards, contractors and working environments with structured security procedures and visible deployment.",
    heroCta: "Request Industrial Assessment",
    heroSecondaryCta: "View Industrial Services",
    aboutTitle: "Built for sites where movement, assets and safety must be controlled.",
    aboutText: "Industrial environments require practical security that understands contractors, deliveries, shift changes, vehicle flow, stock loss, equipment and site safety procedures.",
    vision: "To help operational sites reduce loss and improve site control through practical security procedures.",
    mission: "To secure industrial environments with trained teams, gate control, patrols and structured reporting.",
    values: ["Control", "Safety", "Reliability", "Asset Protection"],
    services: [
      { title: "Industrial Guarding", text: "Security officers for factories, depots, warehouses, logistics yards and construction sites." },
      { title: "Contractor Access Control", text: "Sign-in, induction checks, delivery control and contractor movement procedures." },
      { title: "Yard & Perimeter Patrols", text: "Visible patrols across equipment zones, fence lines, stock areas and parking points." },
      { title: "Stock Loss Prevention", text: "Controls around dispatch, receiving, high-value stores and movement of goods." },
      { title: "Vehicle Gate Control", text: "Truck, delivery and staff vehicle access procedures with clear records." },
      { title: "Safety-Aligned Reporting", text: "Security observations aligned to management, safety and operational review needs." },
    ],
    solutions: ["Warehouse security", "Construction site security", "Logistics yard control", "Factory access management"],
    industries: ["Warehouses", "Factories", "Construction Sites", "Logistics", "Depots", "Industrial Parks"],
    features: ["Gate procedures", "Delivery records", "Stock control", "Perimeter patrols", "Contractor flow", "Incident reports"],
    packages: [
      { title: "Site Access Control", text: "Gate control and contractor sign-in support." },
      { title: "Warehouse Protection", text: "Stock, dispatch and receiving area security." },
      { title: "Construction Security", text: "Equipment, perimeter and after-hours coverage." },
    ],
    stats: [["Assets", "Protected"], ["Controlled", "Gate flow"], ["Logged", "Site movement"], ["Visible", "Perimeter patrols"]],
    process: ["Assess site access and asset risks", "Define gates, patrols and movement controls", "Deploy officers and reporting tools", "Review incidents and improve controls"],
    testimonials: [
      { quote: "The site became easier to control once access and delivery procedures were tightened.", author: "Logistics Manager" },
      { quote: "Their security team understands contractor flow and industrial site risks.", author: "Construction Project Lead" },
    ],
    contactTitle: "Request an industrial security assessment.",
    contactIntro: "Share your site type, gate points, operating hours and key risks so the team can prepare a practical plan.",
  },
  estate: {
    businessName: "Estate Gatehouse Security",
    tagline: "Residential estate security, visitor control, patrols and community-facing protection.",
    motto: "Welcoming. Watchful. Secure.",
    heroTitle: "Residential estate security with professional gatehouse and patrol control.",
    heroSubtitle: "Create a trusted first impression while protecting residents, visitors, service providers and shared spaces.",
    heroCta: "Request Estate Proposal",
    heroSecondaryCta: "View Estate Services",
    aboutTitle: "A residential security template for estates, complexes and apartment communities.",
    aboutText: "Estate security must balance access control, resident experience, visitor screening and visible patrols. This template presents that service in a polished and trust-focused way.",
    vision: "To make communities feel safer through professional, respectful and visible security support.",
    mission: "To protect residential environments with gate control, patrols, communication and resident-focused procedures.",
    values: ["Respect", "Trust", "Visibility", "Community"],
    services: [
      { title: "Gatehouse Control", text: "Resident, visitor, contractor and delivery access procedures for controlled residential entrances." },
      { title: "Visitor Management", text: "Clear visitor capture, confirmation, entry rules and exit control for residential communities." },
      { title: "Estate Patrols", text: "Visible patrols of streets, shared spaces, perimeter points and high-risk areas." },
      { title: "Resident Support", text: "Professional communication, assistance and incident escalation for residents and management." },
      { title: "Contractor Control", text: "Service provider access, working-hour rules and delivery management." },
      { title: "Community Reporting", text: "Reports for trustees, managing agents and estate managers to review activity and incidents." },
    ],
    solutions: ["Estate gatehouse security", "Complex visitor control", "Residential patrols", "Managing-agent reporting"],
    industries: ["Estates", "Complexes", "Apartments", "HOA Communities", "Student Housing", "Residential Parks"],
    features: ["Visitor register", "Resident communication", "Patrol routes", "Contractor control", "Gate procedures", "Management reports"],
    packages: [
      { title: "Gatehouse Essentials", text: "Visitor and resident access control for one entrance." },
      { title: "Estate Patrol Plan", text: "Gate control plus scheduled community patrols." },
      { title: "Managed Community Security", text: "Full residential security with reporting and supervisor support." },
    ],
    stats: [["Calm", "Gate presence"], ["Clear", "Visitor flow"], ["Visible", "Patrols"], ["Trusted", "Community support"]],
    process: ["Review entrances and resident flow", "Create gatehouse and visitor procedures", "Deploy officers and patrol routines", "Report activity to management"],
    testimonials: [
      { quote: "The gatehouse process became more professional and residents noticed the improvement.", author: "Estate Manager" },
      { quote: "They understand how to balance security with resident experience.", author: "Body Corporate Trustee" },
    ],
    contactTitle: "Request an estate security proposal.",
    contactIntro: "Tell us about entrances, number of units, visitor volumes and patrol needs.",
  },
  systems: {
    businessName: "Integrated Security Systems",
    tagline: "CCTV, access control, alarm systems, intercoms and technical security support.",
    motto: "Install. Integrate. Support.",
    heroTitle: "Integrated security systems for smarter site protection and control.",
    heroSubtitle: "A technology-led template for companies installing CCTV, alarms, access control, intercoms and maintenance support.",
    heroCta: "Request Systems Audit",
    heroSecondaryCta: "View System Services",
    aboutTitle: "Designed for security technology installers and system integrators.",
    aboutText: "This template explains technical security services in a way customers can understand: assessment, installation, integration, training, monitoring readiness and ongoing support.",
    vision: "To help clients use security technology that is practical, integrated and maintainable.",
    mission: "To assess, install and support security systems that improve visibility, access control and operational confidence.",
    values: ["Integration", "Reliability", "Clarity", "Support"],
    services: [
      { title: "CCTV Installation", text: "Camera placement, recording setup, remote viewing and coverage recommendations." },
      { title: "Access Control Systems", text: "Tags, biometric readers, door controllers, gates and staff access procedures." },
      { title: "Alarm Systems", text: "Alarm installation, zones, sensors, testing and response workflow support." },
      { title: "Intercom & Gate Automation", text: "Entrance communication, gate access and visitor control technology." },
      { title: "System Maintenance", text: "Preventative maintenance, checks, repairs and client support plans." },
      { title: "Security Technology Audit", text: "Review current systems, coverage gaps, access risks and upgrade opportunities." },
    ],
    solutions: ["CCTV and remote viewing", "Access control integration", "Alarm system setup", "Maintenance and support plans"],
    industries: ["Offices", "Estates", "Retail", "Warehouses", "Schools", "Industrial Sites"],
    features: ["System audits", "Camera planning", "Access setup", "Maintenance plans", "Remote viewing", "Client training"],
    packages: [
      { title: "CCTV Starter System", text: "Camera setup for small offices, shops and homes." },
      { title: "Access Control Package", text: "Door, gate and user access management setup." },
      { title: "Integrated Site System", text: "CCTV, alarms, access and support in one plan." },
    ],
    stats: [["CCTV", "Coverage"], ["Access", "Controlled"], ["Alarms", "Connected"], ["Support", "Maintained"]],
    process: ["Audit the site and technology needs", "Design system and installation plan", "Install, test and train users", "Maintain and support the system"],
    testimonials: [
      { quote: "The system audit helped us understand what to upgrade and what to keep.", author: "Facilities Director" },
      { quote: "Installation was structured and the team explained the system clearly.", author: "Office Manager" },
    ],
    contactTitle: "Request a security systems audit.",
    contactIntro: "Share your site type, existing systems and what you want to install or improve.",
  },
  retail: {
    businessName: "Retail Hospitality Protection",
    tagline: "Customer-friendly security for retail, hospitality, hotels, restaurants and public-facing spaces.",
    motto: "Protective. Polished. Present.",
    heroTitle: "Retail and hospitality security that protects without damaging customer experience.",
    heroSubtitle: "A polished template for security companies serving malls, shops, hotels, restaurants, showrooms and guest-facing venues.",
    heroCta: "Request Service Plan",
    heroSecondaryCta: "View Guest-Facing Services",
    aboutTitle: "Security for brands that need safety and a welcoming first impression.",
    aboutText: "Retail and hospitality security requires professional conduct, loss prevention, guest support and visible presence without intimidating good customers.",
    vision: "To help customer-facing businesses stay safe while preserving a welcoming brand experience.",
    mission: "To provide trained, well-presented officers who support loss prevention, guest safety and front-of-house professionalism.",
    values: ["Presentation", "Awareness", "Service", "Protection"],
    services: [
      { title: "Retail Security", text: "Visible loss-prevention support, customer-friendly presence and incident assistance for stores and malls." },
      { title: "Hotel & Guest Security", text: "Lobby, event, parking and guest-area support with professional conduct." },
      { title: "Restaurant Security", text: "Door control, closing support, parking visibility and guest-flow assistance." },
      { title: "Loss Prevention", text: "Observation, floor presence, incident notes and support around stock and high-risk zones." },
      { title: "Front-Of-House Presence", text: "Polished officers suited for branded venues, receptions and public-facing entrances." },
      { title: "Incident Assistance", text: "Support for guest disputes, suspicious activity, escorts and escalation communication." },
    ],
    solutions: ["Shop and mall security", "Hotel lobby support", "Restaurant closing support", "Loss-prevention presence"],
    industries: ["Retail Stores", "Shopping Centres", "Hotels", "Restaurants", "Showrooms", "Entertainment Venues"],
    features: ["Brand-friendly officers", "Loss prevention", "Guest support", "Incident notes", "Closing checks", "Public-facing presence"],
    packages: [
      { title: "Retail Floor Presence", text: "Visible customer-friendly loss-prevention support." },
      { title: "Hospitality Front Desk Support", text: "Lobby, guest-area and parking visibility." },
      { title: "Evening Closing Plan", text: "Closing checks, escorts and after-hours presence." },
    ],
    stats: [["Polished", "Front-of-house"], ["Aware", "Loss prevention"], ["Helpful", "Guest support"], ["Clear", "Incident notes"]],
    process: ["Review customer flow and risk areas", "Match officer profile to brand environment", "Deploy visible and professional presence", "Report incidents and improvement notes"],
    testimonials: [
      { quote: "The officers are professional and fit our customer-facing environment well.", author: "Hotel Operations Manager" },
      { quote: "We improved floor visibility and incident reporting without making customers uncomfortable.", author: "Retail Store Owner" },
    ],
    contactTitle: "Request a retail or hospitality security plan.",
    contactIntro: "Tell us about your venue, hours, guest flow and security concerns.",
  },
};

export const SECURITY_PRESETS = {
  "security-guarding-v1": {
    template_key: "security-guarding-v1",
    name: "Guarding Command",
    contentKey: "guarding",
    theme: "command",
    imagePack: "guarding",
    structure: "guarding",
    navbarVariant: "command",
    heroVariant: "split-command",
    vmvVariant: "command-panels",
    cardVariant: "patrol-cards",
    footerVariant: "operations-footer",
    formVariant: "site-assessment",
  },
  "security-surveillance-v1": {
    template_key: "security-surveillance-v1",
    name: "Surveillance Control",
    contentKey: "surveillance",
    theme: "matrix",
    imagePack: "surveillance",
    structure: "surveillance",
    navbarVariant: "tech-glass",
    heroVariant: "monitoring-dashboard",
    vmvVariant: "radar-grid",
    cardVariant: "camera-cards",
    footerVariant: "control-room-footer",
    formVariant: "monitoring-plan",
  },
  "security-executive-v1": {
    template_key: "security-executive-v1",
    name: "Executive Shield",
    contentKey: "executive",
    theme: "executive",
    imagePack: "executive",
    structure: "executive",
    navbarVariant: "premium",
    heroVariant: "executive-suite",
    vmvVariant: "premium-panels",
    cardVariant: "executive-cards",
    footerVariant: "executive-footer",
    formVariant: "confidential-consultation",
  },
  "security-event-v1": {
    template_key: "security-event-v1",
    name: "Event Shield Operations",
    contentKey: "event",
    theme: "event",
    imagePack: "event",
    structure: "event",
    navbarVariant: "event-alert",
    heroVariant: "event-command",
    vmvVariant: "event-blocks",
    cardVariant: "event-cards",
    footerVariant: "event-footer",
    formVariant: "event-plan",
  },

  "security-mobile-patrol-v1": {
    template_key: "security-mobile-patrol-v1",
    name: "Mobile Patrol Response",
    contentKey: "patrol",
    theme: "patrol",
    imagePack: "patrol",
    structure: "patrol",
    navbarVariant: "patrol-stripe",
    heroVariant: "patrol-route",
    vmvVariant: "patrol-panels",
    cardVariant: "route-cards",
    footerVariant: "patrol-footer",
    formVariant: "patrol-response",
  },
  "security-alarm-response-v1": {
    template_key: "security-alarm-response-v1",
    name: "Rapid Alarm Response",
    contentKey: "alarm",
    theme: "alarm",
    imagePack: "alarm",
    structure: "alarm",
    navbarVariant: "alarm-pulse",
    heroVariant: "response-alert",
    vmvVariant: "alarm-blocks",
    cardVariant: "response-cards",
    footerVariant: "alarm-footer",
    formVariant: "alarm-response",
  },
  "security-industrial-v1": {
    template_key: "security-industrial-v1",
    name: "Industrial Shield",
    contentKey: "industrial",
    theme: "industrial",
    imagePack: "industrial",
    structure: "industrial",
    navbarVariant: "industrial-steel",
    heroVariant: "industrial-grid",
    vmvVariant: "industrial-panels",
    cardVariant: "industrial-cards",
    footerVariant: "industrial-footer",
    formVariant: "industrial-plan",
  },
  "security-estate-v1": {
    template_key: "security-estate-v1",
    name: "Estate Gatehouse",
    contentKey: "estate",
    theme: "estate",
    imagePack: "estate",
    structure: "estate",
    navbarVariant: "estate-clean",
    heroVariant: "estate-welcome",
    vmvVariant: "estate-panels",
    cardVariant: "estate-cards",
    footerVariant: "estate-footer",
    formVariant: "estate-security",
  },
  "security-systems-v1": {
    template_key: "security-systems-v1",
    name: "Integrated Systems",
    contentKey: "systems",
    theme: "systems",
    imagePack: "systems",
    structure: "systems",
    navbarVariant: "systems-blueprint",
    heroVariant: "systems-console",
    vmvVariant: "systems-grid",
    cardVariant: "systems-cards",
    footerVariant: "systems-footer",
    formVariant: "systems-installation",
  },
  "security-retail-hospitality-v1": {
    template_key: "security-retail-hospitality-v1",
    name: "Retail Hospitality Protection",
    contentKey: "retail",
    theme: "retail",
    imagePack: "retail",
    structure: "retail",
    navbarVariant: "retail-polished",
    heroVariant: "retail-showcase",
    vmvVariant: "retail-panels",
    cardVariant: "retail-cards",
    footerVariant: "retail-footer",
    formVariant: "retail-service",
  },

};
